#此文件配置修改后重启和reload才会生效

whitelist:
  #白名单总开关 添加白名单命令 /bai add
  whitelistCheckSwitch: false

ipLogin:
  #IP登录总开关
  ipLoginCheckSwitch: false

#此功能连接QQ机器人尚未开发
webSocket:
  #WebSocket总开关
  webSocketCheckSwitch: false
  webSocketUrl: ws://localhost:8080/