#请不要删除任何配置，否则会影响系统运行
password:
  #密码检测总控开关
  passwordCheckSwitch: true
  #密码长度控制开关
  checkPasswordLength: true
  #密码最小长度
  limitPasswordMinLength: 6
  #密码最大长度
  limitPasswordMaxLength: 20
  #密码是否必须包含数字
  checkContainDigit: true
  #密码是否必须包含字母
  checkContainUpperLowerCase: true
  #密码是否必须包含小写字母
  checkContainLowerCase: false
  #密码是否必须包含大写字母
  checkContainUpperCase: false
  #密码是否必须包含特殊字符
  checkContainSpecialChar: false
  #密码中不允许的字符集合
  defaultSpecialChar: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
  #键盘横向连续检测开关，如qwer等
  checkHorizontalKeySequential: false
  #键盘横向连续检测最小长度 配置3 qw可以通过检测 qwr qwer qwerty等都无法通过检测
  limitHorizontalKeyNumber: 3
  #键盘斜向连续检测开关 如qaz、wsx edc rfv等
  checkSlopeKeySequential: false
  #键盘斜向连续检测最小长度 最大只能只能是3
  limitSlopeKeyNumber: 3
  #逻辑位置连续检测开关，如1234、abcd等
  checkLogicSequential: false
  #逻辑位置连续检测最小长度
  limitLogicNumber: 4
  #相邻字符相同检测开关，如aaa、111、###等
  checkSequentialCharSame: false
  #相邻字符相同检测最小长度
  limitSequentialCharNumber: 3
  #自定义密码检测开关，如固定字符等 此功能是配置黑名单字符串的开关 此版本暂时不支持
  checkCustomPasswordArray: true
