#项目名称
name: YMLogin
#版本号
version: '${project.version}'
#启动类类名
main: com.ym.ymlogin.YMLogin
#游戏大版本
api-version: 1.20
#作者
authors: [ YiMeng ]
#插件描述
description: 忆梦登录插件
#插件官网
website:
#load 插件的加载方式
# STARTUP在服务器加载世界前启动插件
# POSTWORLD 在世界加载完后启动插件 这个是默认值
load: POSTWORLD
#设置服务器依赖的插件，没有就不能运行,自己插件在他们加载之后再加载
#depend:
#  - xxx
#  - xxx
#设置服务器软依赖的插件，这里的插件不是必须的，脱离是可以运行的,自己插件在他们加载之后再加载
#sortdepend:
#  - xxx
#  - xxx

#自己的插件会在这个列表的插件之前被加载
#loadbefore:
#  - xxx
#  - xxx

#声明插件希望注册的权限
permissions:
#注册插件需要用到的指令
commands:
  login:
    description: /login <登录密码>
    usage: /login <password>
  register:
    description: /register <密码> <第二次输入密码>
    usage: /register <password> <password>
    aliases: ["reg"]


#修改日志的前缀
perfix: YMLoginPlugin
# player_passwords.yml
